# Generated by Django 3.2.9 on 2022-02-04 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='town',
            old_name='town',
            new_name='city',
        ),
    ]
